import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { token, markdown, description } = await req.json();

    if (!token) {
      return NextResponse.json({ error: 'Token is required' }, { status: 400 });
    }

    const res = await fetch('https://api.github.com/gists', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
        'User-Agent': 'README-Builder-App',
      },
      body: JSON.stringify({
        description: description || 'GitHub Profile README — generated by README Builder (InfernalShark)',
        public: true,
        files: {
          'README.md': {
            content: markdown || '# Empty README',
          },
        },
      }),
    });

    const data = await res.json();

    if (!res.ok) {
      return NextResponse.json(
        { error: data.message || 'Failed to publish Gist' },
        { status: res.status }
      );
    }

    return NextResponse.json({ html_url: data.html_url });
  } catch (err: any) {
    return NextResponse.json(
      { error: err.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}
