'use client';
import React, { useState, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import { Copy, Download, GitBranch, Check, Eye, Code, ExternalLink } from 'lucide-react';
import { useReadmeStore } from '@/store/useReadmeStore';
import { useLanguageStore } from '@/store/useLanguageStore';
import { generateMarkdown } from '@/lib/markdownGenerator';
import { Button } from '@/components/ui/Button';
import { GistModal } from '@/components/ui/GistModal';
import { t } from '@/lib/i18n';
import { cn } from '@/lib/utils';

type Tab = 'rendered' | 'raw';

export function MarkdownPreview() {
  const { username, blocks } = useReadmeStore();
  const { lang } = useLanguageStore();
  const [tab, setTab] = useState<Tab>('rendered');
  const [copied, setCopied] = useState(false);

  // Gist state
  const [gistModalOpen, setGistModalOpen] = useState(false);
  const [gistLoading, setGistLoading] = useState(false);
  const [gistUrl, setGistUrl] = useState<string | null>(null);
  const [gistError, setGistError] = useState<string | null>(null);

  const markdown = generateMarkdown(username, blocks);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const el = document.createElement('textarea');
      el.value = markdown;
      document.body.appendChild(el);
      el.select();
      document.execCommand('copy');
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [markdown]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'README.md';
    a.click();
    URL.revokeObjectURL(url);
  }, [markdown]);

  const handlePublishGist = useCallback(
    async (token: string) => {
      setGistLoading(true);
      setGistError(null);
      setGistUrl(null);

      try {
        const res = await fetch('/api/gist', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            token,
            markdown: markdown || '# Empty README',
            description: 'GitHub Profile README — generated by README Builder (InfernalShark)',
          }),
        });

        const data = await res.json();

        if (!res.ok) {
          throw new Error(data.error || `HTTP ${res.status}`);
        }

        setGistUrl(data.html_url);
        setGistModalOpen(false);
      } catch (err: unknown) {
        const message =
          err instanceof Error
            ? err.message
            : typeof err === 'string'
            ? err
            : 'Unknown error';
        setGistError(message);
        // Keep modal open so user can retry or see the error
      } finally {
        setGistLoading(false);
      }
    },
    [markdown]
  );

  return (
    <div className="flex flex-col h-full bg-[#080808]">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-white/[0.06] bg-[#0a0a0a] flex-shrink-0">
        {/* Tabs */}
        <div className="flex items-center gap-1 bg-white/[0.04] rounded-lg p-1">
          <button
            onClick={() => setTab('rendered')}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all duration-150',
              tab === 'rendered'
                ? 'bg-white/10 text-white shadow-sm'
                : 'text-neutral-500 hover:text-neutral-300'
            )}
          >
            <Eye size={12} />
            {t(lang, 'rendered')}
          </button>
          <button
            onClick={() => setTab('raw')}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all duration-150',
              tab === 'raw'
                ? 'bg-white/10 text-white shadow-sm'
                : 'text-neutral-500 hover:text-neutral-300'
            )}
          >
            <Code size={12} />
            {t(lang, 'raw')}
          </button>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5">
            {copied ? <Check size={13} className="text-green-400" /> : <Copy size={13} />}
            {copied ? t(lang, 'copied') : t(lang, 'copy')}
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5">
            <Download size={13} />
            {t(lang, 'download')}
          </Button>
          <Button
            variant="primary"
            size="sm"
            onClick={() => {
              setGistError(null);
              setGistModalOpen(true);
            }}
            disabled={gistLoading}
            className="gap-1.5"
          >
            <GitBranch size={13} />
            {t(lang, 'publishGist')}
          </Button>
        </div>
      </div>

      {/* Gist success banner */}
      {gistUrl && !gistModalOpen && (
        <div className="flex items-center gap-2 px-4 py-2 text-xs border-b bg-green-500/10 border-green-500/20 text-green-400 flex-shrink-0">
          <Check size={12} />
          {t(lang, 'published')}
          <a
            href={gistUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="underline flex items-center gap-1 hover:text-green-300 transition-colors"
          >
            {t(lang, 'viewGist')} <ExternalLink size={10} />
          </a>
        </div>
      )}

      {/* Gist error banner (shown outside modal if modal was closed) */}
      {gistError && !gistModalOpen && (
        <div className="flex items-center gap-2 px-4 py-2 text-xs border-b bg-red-500/10 border-red-500/20 text-red-400 flex-shrink-0">
          ⚠️ {gistError}
        </div>
      )}

      {/* Content */}
      <div className="flex-1 overflow-y-auto custom-scrollbar">
        {tab === 'rendered' ? (
          <div className="p-6 max-w-3xl mx-auto">
            {markdown ? (
              <div
                className="prose prose-invert prose-sm max-w-none
                  prose-headings:text-neutral-100 prose-headings:font-semibold
                  prose-p:text-neutral-300 prose-p:leading-relaxed
                  prose-a:text-indigo-400 prose-a:no-underline hover:prose-a:underline
                  prose-code:text-indigo-300 prose-code:bg-white/5 prose-code:px-1 prose-code:py-0.5 prose-code:rounded
                  prose-pre:bg-white/5 prose-pre:border prose-pre:border-white/10
                  prose-blockquote:border-l-indigo-500 prose-blockquote:text-neutral-400
                  prose-hr:border-white/10
                  prose-img:rounded-lg prose-img:mx-auto
                  prose-strong:text-neutral-100
                  prose-li:text-neutral-300"
              >
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  rehypePlugins={[rehypeRaw]}
                  components={{
                    img: ({ src, alt, ...props }) => (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img
                        src={src}
                        alt={alt ?? ''}
                        className="max-w-full h-auto rounded-lg"
                        {...props}
                      />
                    ),
                  }}
                >
                  {markdown}
                </ReactMarkdown>
              </div>
            ) : (
              <EmptyState lang={lang} />
            )}
          </div>
        ) : (
          <div className="p-4">
            <pre className="text-xs text-neutral-300 font-mono whitespace-pre-wrap break-words leading-relaxed bg-white/[0.03] border border-white/[0.06] rounded-xl p-4">
              {markdown || '# Your README will appear here…'}
            </pre>
          </div>
        )}
      </div>

      {/* Gist Modal */}
      <GistModal
        isOpen={gistModalOpen}
        onClose={() => setGistModalOpen(false)}
        onPublish={handlePublishGist}
        isLoading={gistLoading}
      />
    </div>
  );
}

function EmptyState({ lang }: { lang: import('@/lib/i18n').Lang }) {
  return (
    <div className="flex flex-col items-center justify-center h-64 gap-4 text-center">
      <div className="w-16 h-16 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center">
        <GitBranch size={28} className="text-indigo-400" />
      </div>
      <div>
        <p className="text-neutral-300 font-medium">{t(lang, 'noContent')}</p>
        <p className="text-neutral-600 text-sm mt-1">{t(lang, 'noContentHint')}</p>
      </div>
    </div>
  );
}
